apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: route-injector
spec:
  selector:
    matchLabels:
      name: route-injector
  template:
    metadata:
      labels:
        name: route-injector
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      containers:
        - name: route-setup
          image: alpine
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "[INFO] Checking route to 10.7.7.0/24 via ${OCSERV_POD_IP}..."
              if ip route | grep -q "10.7.7.0/24 via ${OCSERV_POD_IP}"; then
                echo "[INFO] Route already exists"
              else
                echo "[INFO] Adding route"
                ip route del 10.7.7.0/24 2>/dev/null || true
                ip route add 10.7.7.0/24 via ${OCSERV_POD_IP}
              fi
              sleep infinity