apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: route-injector-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["create", "delete", "get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: route-injector-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: route-injector-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: route-injector-sa
    namespace: default
roleRef:
  kind: Role
  name: route-injector-role
  apiGroup: rbac.authorization.k8s.io